apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-cicd-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-cicd-app
  template:
    metadata:
      labels:
        app: devops-cicd-app
    spec:
      containers:
      - name: devops-cicd-container
        image: meghaamanickam/devops-cicd-app:latest
        ports:
        - containerPort: 3000
